### ISSUE TITLE
How to Restrict Entity Deletion Permission with Keycloak Integration

### ISSUE THREAD

**Issue by dr-yst** [stellio-hub/stellio-context-broker#1243]
Hello Stellio Team,

I am currently integrating Stellio Context Broker with Keycloak for access control and would like to know how to restrict the deletion of entities based on user roles.
Specifically, I want to ensure that certain users do not have permission to delete entities, but can still view and update them.

Could you please provide guidance or point me to any documentation on how to achieve this?
Any advice or best practices for configuring Keycloak policies or Stellio’s security settings would be greatly appreciated.

Thank you for your support!

**Comment by bobeal** [comment]
Hi @dr-yst,

You will find some information in https://stellio.readthedocs.io/en/latest/user/authentication_and_authorization.html. Only high level roles are defined in Keycloak (https://stellio.readthedocs.io/en/latest/admin/keycloak_integration.html#create-the-builtin-roles), rights on entities are managed inside Stellio (since it is hard for Keycloak to know all the existing entities).

Only the owner of an entity or someone having admin role on the entity can delete it.

Let me know if you need more details.

**Comment by dr-yst** [comment]
@bobeal 
Thank you for getting back to me.
I understood we can control access policy through the Stellio's API, not Keycloak.

So, is it proper behavior for Keycloak's built-in role "stellio-creator" to be able to not only create entities, but also delete entities created by the same client?
We confirmed this behavior.

**Comment by bobeal** [comment]
> @bobeal Thank you for getting back to me. I understood we can control access policy through the Stellio's API, not Keycloak.

Yes, exactly.

> So, is it proper behavior for Keycloak's built-in role "stellio-creator" to be able to not only create entities, but also delete entities created by the same client? We confirmed this behavior.

Indeed, a user is allowed to delete the entities he created / is owner of. Not other entities of course.

**Comment by dr-yst** [comment]
@bobeal 
Thank you very much!
I now know what I want to know and it is resolved.
