### ISSUE TITLE
Review the usages of InvalidRequest and BadRequestData error responses

### ISSUE THREAD

**Issue by bobeal** [stellio-hub/stellio-context-broker#188]
It seems like there has been some mismatch between these 2 error responses and some BadRequestData errors are sent where it is expected to send InvalidRequest errors (and maybe the opposite is also true).

**Comment by HoucemKacem** [comment]
- InvalidRequest that should be a BadRequestData:
There is no InvalidRequest that should be changed to a BadRequestData since we are not returning InvalidRequest exceptions.

- BadRequestData that should be a InvalidRequest:

    1. Currently, if we encounter a JsonParseException (from com.fasterxml.jackson.core) we return a JsonParseErrorResponse 
```
data class JsonParseErrorResponse(override val detail: String) : ErrorResponse(
    ErrorType.BAD_REQUEST_DATA.type,
    "The request includes invalid input data, an error occurred during JSON parsing",
    detail
)
```
From 5.5.4, an InvalidRequest should be returned, then i suggest the following changes:
```
data class JsonParseErrorResponse(override val detail: String) : ErrorResponse(
    ErrorType.INVALID_REQUEST.type,
    "The request includes invalid input data, an error occurred during JSON parsing",
    detail
)
```

**Comment by bobeal** [comment]
LGTM
