### ISSUE TITLE
Updates on (a same) Context file are not taken into account

### ISSUE THREAD

**Issue by AHABID** [stellio-hub/stellio-context-broker#346]
When using a same url of a context file (i.e. used before to create entities) and when updating this file by adding some new attributes definitions, the new updates are not taken into account and new attributes are directly mapped to the default context.

Example:
I'm using this context [file](https://github.com/easy-global-market/ngsild-api-data-models/blob/master/aquaculture/jsonld-contexts/aquacultureCompouned.jsonld) to create entities. I have updated one of its [sub-context](https://raw.githubusercontent.com/easy-global-market/ngsild-api-data-models/master/aquaculture/jsonld-contexts/aquaculture.jsonld). New added attributes to the context are mapped with the default context

**Comment by bobeal** [comment]
Indeed, the JSON-LD library we are using is doing aggressive caching. At first look, I'm not even sure a cached context ever expires (but to be checked)...

We have to investigate how to refresh a cached context (without restarting the server, of course).

**Comment by bobeal** [comment]
As discussed, when updating your context in "dev mode", you can use an URL referencing directly the commit where you introduced your new properties. For instance, https://raw.githubusercontent.com/easy-global-market/ngsild-api-data-models/51a185144aa6f598ebf63d7de544930cd75d0eb3/aquaculture/jsonld-contexts/aquacultureCompouned.jsonld instead of https://raw.githubusercontent.com/easy-global-market/ngsild-api-data-models/master/aquaculture/jsonld-contexts/aquacultureCompouned.jsonld.

**Comment by AHABID** [comment]
This works perfectly for entity-service but when using the temporal API I have the same issue.

**Comment by bobeal** [comment]
> This works perfectly for entity-service but when using the temporal API I have the same issue.

Are you sure your temporal entity has not been created before using the new context (so with expanded names on the core context and not your context)?

**Comment by bobeal** [comment]
I think it is fixed. Re-open it if not.
