### ISSUE TITLE
Fix entity property value array of strings returning as a string

### ISSUE THREAD

**Issue by junjou** [stellio-hub/stellio-context-broker#419]
Creating entity (urn:ngsi-ld:AlertPlan:PostmanArray05) with array as property value:
![image](https://user-images.githubusercontent.com/36960251/119504975-c722db00-bd6c-11eb-8e76-ab8b1b01376f.png)

When querying entity:
![image](https://user-images.githubusercontent.com/36960251/119505106-ea4d8a80-bd6c-11eb-8035-507a2f30f2fe.png)

Problem disapears when array length > 1 (querying urn:ngsi-ld:AlertPlan:PostmanArray04):
![image](https://user-images.githubusercontent.com/36960251/119505426-3b5d7e80-bd6d-11eb-9955-927b5d305d60.png)

**Comment by bobeal** [comment]
This has been discussed with NGSI-LD standardization group and, unfortunately, this can't be solved due to how JSON-LD expansion works (after expansion, values are always in a list and it's not possible to know if it was previously a list of one or a string). So this is considered a valid behavior (even though we are kind of losing part of the semantics).
