### ISSUE TITLE
Attribute names are not fully compacted

### ISSUE THREAD

**Issue by jason-fox** [stellio-hub/stellio-context-broker#657]
In Stellio 1.7.2, I create the following entity including two contexts:

```console
curl -L -X POST 'http://localhost:8080/ngsi-ld/v1/entities/' \
-H 'Content-Type: application/ld+json' \
--data-raw '{
    "id": "urn:ngsi-ld:Building:store001",
    "type": "Building",
    "category": {
    	"type": "Property",
        "value": ["commercial"]
    },
    "address": {
        "type": "Property",
        "value": {
            "streetAddress": "Bornholmer Straße 65",
            "addressRegion": "Berlin",
            "addressLocality": "Prenzlauer Berg",
            "postalCode": "10439"
        },
        "verified": {
			"type": "Property",
			"value": true
		}
    },
    "location": {
        "type": "GeoProperty",
        "value": {
             "type": "Point",
             "coordinates": [13.3986, 52.5547]
        }
    },
    "name": {
        "type": "Property",
        "value": "Bösebrücke Einkauf"
    },
    "@context": [
        "https://smartdatamodels.org/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld"
    ]
}'
```

I  then retrieve the entity by `type`:

```console
curl -L -X GET 'http://localhost:8080/ngsi-ld/v1/entities?type=Building' \
-H 'Link: <https://smartdatamodels.org/context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Accept: application/ld+json'
```

```json
[
    {
        "id": "urn:ngsi-ld:Building:store001",
        "type": "Building",
        "address": {
            "type": "Property",
            "verified": {
                "type": "Property",
                "value": true
            },
            "value": {
                "addressLocality": "Prenzlauer Berg",
                "addressRegion": "Berlin",
                "postalCode": "10439",
                "streetAddress": "Bornholmer Straße 65"
            }
        },
        "category": {
            "type": "Property",
            "value": "commercial"
        },
        "ngsi-ld:location": {
            "type": "GeoProperty",
            "value": "POINT (13.3986 52.5547)"
        },
        "name": {
            "type": "Property",
            "value": "Bösebrücke Einkauf"
        },
        "@context": [
            "https://smartdatamodels.org/context.jsonld"
        ]
    }
]
```
1. `location` is not fully compacted.
2.  `location` value is displayed  incorrectly. It should display as:

```json
 {
             "type": "Point",
             "coordinates": [13.3986, 52.5547]
 }
```

3. The `@context` is missing the core context:

```json
 "@context": [
        "https://smartdatamodels.org/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld"
    ]
```

**Comment by bobeal** [comment]
Hi @jason-fox,

Actually, Stellio is v1.3 compatible only since v1.8.0 (https://github.com/stellio-hub/stellio-context-broker/releases/tag/v1.8.0) and you're using v1.7.2. That explains the problem with the `location` attribute.

It may also explain some other issues you had, I'll look at them carefully in the next days.

**Comment by jason-fox** [comment]
I have just rechecked with v1.8.0

```
curl -L -X GET 'http://localhost:8080/ngsi-ld/v1/entities?type=Building' \
-H 'Link: <https://smartdatamodels.org/context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Accept: application/ld+json'
```

still returns elements  such as:

```json
 "ngsi-ld:location": {
            "type": "GeoProperty",
            "value": "POINT (13.3986 52.5547)"
}
```

**Comment by bobeal** [comment]
Strange, it works fine on our deployments. Let me investigate.

PS: I've checked the other issues, results are as expected as they make use of parts of the NGSI-LD query language which are not implemented in Stellio.

**Comment by bobeal** [comment]
In `https://smartdatamodels.org/context.jsonld`, `location` is defined as `http://uri.etsi.org/ngsi-ld/location` (whereas it is defined as `https://uri.etsi.org/ngsi-ld/location` in the core context).

At creation time, `location` is expanded to `https://uri.etsi.org/ngsi-ld/location` since the core context is also provided in the query.

When doing a query on the entities, as the provided context (`https://smartdatamodels.org/context.jsonld`) already includes many terms from the core context, Stellio thinks the core context is already included and does not add it. Then the compaction of the `location` attribute is faulty since its definition is incorrect in the provided context.

Stellio could maybe (not even sure) do a better job at deciding if the core context is already present but it will have a cost. And I personally think that the cherry-picking of core context terms into user contexts should be avoided as it is confusing, hard to maintain and error prone.
