### ISSUE TITLE
kubernetes deployment not OK for stellio without neo4j

### ISSUE THREAD

**Issue by agaldemas** [stellio-hub/stellio-context-broker#842]
Hello @bobeal 

I wanted to use the new stellio version, without neo4j...
then I tried to deploy stellio using last kubernetes yaml files from develop branch, but there is a problem, the database "stellio_subscription"  is not created !

I took back my old yaml files working, and the database "stellio_subscription" was created, I don't catch why...
I had also to take the kafka-values.yaml that I modified, to run kafka, and to deploy zookeeper

But when I try some requests but I have 500 error, and api-gateway logs tell entity-service is missing, but it has been removed from the kubernetes directory ?

I suppose that kubernetes deployment is not yet ready without neo4j...

Thanks in advance for your feedback

**Comment by agaldemas-eridanis** [comment]
connected with my other account on eridanis.com, to be involved

**Comment by bobeal** [comment]
Hi @agaldemas-eridanis,

Indeed, we have not yet tested (nor totally updated) the k8s configuration.

Some inputs:
- we use a new base Docker image for PG (https://github.com/kartoza/docker-postgis), so the config has changed a bit, that explains why the DB is no longer created
- we also switched to new Kafka version that does no longer need Zookeeper, this has to be updated in the Kafka config
- and entity-service no longer exists, its features have been merged in search-service (which now needs a better name btw)

We have plans to work on an updated k8s deployment soon.

Meanwhile, if you feel brave enough to update the configuration :) (the `docker-compose.yml` file in the root directory is fully up-to-date, it can be used for inspiration)

**Comment by agaldemas-eridanis** [comment]
Hi Benoit, OK, I've just seen your answer, thanks,

by reinstalling from scratch, I managed to get components working, with images tagged "latest" for search-service, subscription-service, & tag "2.1.0-dev" for api-gateway.
I still need to fix things, with your hints, with the new kafka config...

But for the moment when I request the api-gateway, I always get 404 error, (instead of the 500) whatever the request is, like api-gateway can't reach search-service !
and I found this error in logs:

```
2023-02-02 17:37:57,181 [or-http-epoll-5] INFO LoggingFilter - log - [3dba91fd-3, L:/10.42.2.52:49824 - R:search-service.hdp-stellio-services.svc.cluster.local/10.43.199.178:8083] WRITE: 629B GET /ngsi-ld/v1/entities/ HTTP/1.1
Link: <https://raw.githubusercontent.com/easy-global-market/ngsild-api-data-models/master/apic/jsonld-contexts/apic-compound.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Postman-Token: ...
Accept-Encoding: gzip, deflate, br
Forwarded: proto=http;host="localhost:8080";for="127.0.0.1:47616"
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
X-Forwarded-Port: 8080
X-Forwarded-Host: localhost:8080
host: search-service:8083
content-length: 0
2023-02-02 17:37:57,181 [or-http-epoll-5] INFO LoggingFilter - log - [3dba91fd-3, L:/10.42.2.52:49824 - R:search-service.hdp-stellio-services.svc.cluster.local/10.43.199.178:8083] FLUSH
2023-02-02 17:37:57,191 [or-http-epoll-5] INFO LoggingFilter - log - [3dba91fd-3, L:/10.42.2.52:49824 - R:search-service.hdp-stellio-services.svc.cluster.local/10.43.199.178:8083] READ: 408B HTTP/1.1 404 Not Found
Content-Type: application/json
Content-Length: 116
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1 ; mode=block
Referrer-Policy: no-referrer
{"timestamp":1675359477186,"path":"/ngsi-ld/v1/entities/","status":404,"error":"Not Found","requestId":"066b07c7-3"}
2023-02-02 17:37:57,198 [or-http-epoll-5] INFO LoggingFilter - log - [3dba91fd, L:/10.42.2.52:49824 - R:search-service.hdp-stellio-services.svc.cluster.local/10.43.199.178:8083] READ COMPLETE
```
nothing in search-service logs
I don't catch where is the problem, probably in api-gateway...

and I'am asking myself: does the request goes through kafka between api-gateway and search-service ? or it's just for managing subscriptions ?

In that case I need to fix the kafka configuration first...
thanks to confirm !

**Comment by bobeal** [comment]
Hi @agaldemas-eridanis,

It seems like you are using a mix of v1.x and v2.x. We've changed a bit how the tags are managed in Stellio (https://github.com/stellio-hub/stellio-context-broker#docker-images-tagging). You should use either `2.0.0` (or `2.1.0-dev` if you feel brave) for all the services. `latest` is still pointing to v1.x (and will soon be removed to avoid such misunderstandings), this is way you have a 404.

When you call `api-gateway`, the request goes directly to `search-service` without involving Kafka (it happens here: https://github.com/stellio-hub/stellio-context-broker/blob/develop/api-gateway/src/main/kotlin/com/egm/stellio/apigateway/ApiGatewayApplication.kt#L27).

**Comment by agaldemas-eridanis** [comment]
Hello, good news, I managed to get stellio running & **working** in 2.0.0, on kubernetes.

I don't promise you, but I'll make a PR, asap, but I won't have a lot of time to test on minikube.
I have just added a configmap for kafka to load update_run.sh, and added "sh" before the command.
transposed new kafka parameters in deployment.yaml (using `kompose convert` on docker-compose.yml, it's simple).

Next step should be to prepare an **helm chart**, since it will be better to manage, and it will insure having necessary k8s parameters for production deployments...

But how do you prefer : to have the helm chart in this project , or to have a special project stellio-helm ?

I think having a special project is better, If you're OK, I'll start one on [eridanisfr](https://github.com/eridanisfr), our public github.

Looking forward reading you

**Comment by bobeal** [comment]
Glad to hear that!

If you do a PR, I'll take some time to test it on Minikube :)

I agree with you, a separate project is better. I'll add a link to it in the README.md so that it is easy to find.

**Comment by profijoeln** [comment]
Hello, Any update on this Kubernetes deployment PR ?

We would be interested in using it!

**Comment by agaldemas-eridanis** [comment]
Sorry, not yet had time to do the PR, and the helm project

**Comment by agaldemas-eridanis** [comment]
Me again @bobeal 
I have a question regarding Stellio and more generally context broker deployment and NGSI-LD context: 

Don't you think it could be valuable to add @context file web server deployment artifacts for kubernetes deployment of NGSI-LD context brokers ?
I think to integrate this feature in the helm chart, but it might be useful in this repo too !
It's just matter to add a web server pod, where the context file is used through a configMap, or something like...
I've to do this now, because we need it urgently for our current project, before working on the helm chart....
If you like I can also make a PR for this feature ?

**Comment by bobeal** [comment]
> Don't you think it could be valuable to add @context file web server deployment artifacts for kubernetes deployment of NGSI-LD context brokers ?

TBH, I don't really get the link between serving @contexts and k8s deployment :) 

The NGSI-LD specification has something for this (see 5.13 in the specification) but it is not yet implemented in Stellio (https://github.com/stellio-hub/stellio-context-broker/issues/682)

Another option (a bit dirty since you need to modify Stellio) is to do something like this: https://github.com/stellio-hub/stellio-context-broker/commit/95f16dac5ed9ac617b11bd7d074e327f6dd37811

**Comment by agaldemas-eridanis** [comment]
Hello Benoit,
I'm currently adding some k8s artefacts to deploy @context file server:
- first I added `ld-context` (`image: httpd:alpine`) service in the docker-compose.yml
- I added a directory to hold jsonld @context file
- from the docker-compose.yml file I have generated k8s artefacts with `kompose convert`
- also added a command to deploy the @context file in a ConfigMap for the `ld-context` pod, to serve it !
- I'll do a specific PR for that, but for the moment I'm working on our own gitlab repo.
- then in the stellio-helm, I will also include a way to deploy the @context file server.

**Comment by bobeal** [comment]
OK, let me know how it goes and if I can help.

In the medium term, we'll add support for the storage and serving of contexts that will serve a similar purpose.

**Comment by agaldemas-eridanis** [comment]
hello @bobeal, @profijoeln, in my PR, you'll find a working set of yaml files to deploy stellio under Kubernetes !
