### ISSUE TITLE
Is Stelio using Neo4j?

### ISSUE THREAD

**Issue by Manifesto24** [stellio-hub/stellio-context-broker#972]
Is Stellio using Neo4J as a database for the entities ? Or is it using TimescaleDB and PostGIS? Seems like I cannot find any information related with neo4j from the source code.

**Comment by bobeal** [comment]
Hello,

Stellio was using Neo4j but it has been replaced since version 2.0.0 (https://stellio.readthedocs.io/en/latest/admin/upgrading_to_2.0.0.html) and Stellio now only uses PostgreSQL with PostGIS and TimescaleDB (you can find an high level overview here: https://stellio.readthedocs.io/en/latest/quick_start_guide.html).
